--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AlecksWasHere/NicknameManager
build-by-default: true
branches:
  - PM4
projects:
  ChatFX:
    path: ""
    libs:
      - src: Vecnavium/FormAPI/libFormAPI
        version: ^1.3
...
