--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alacksch/ChatFX
build-by-default: true
branches:
- main
projects:
  ChatFX:
    path: ""
    libs:
      - src: Frago9876543210/forms/libforms
        version: ^1.0.0
...
