---
name: ChatFX
version: 0.0.1
main: Alacksch\ChatFX\ChatFX
api: 5.17.0
src-namespace-prefix: Alacksch\ChatFX
depend:
  - forms
permissions:
  chatfx.cmd:
    default: true
  chatfx.cfx:
    default: true
